/******************************************************************************
	Description
		Main Function. Original code generated by CubeMX.
    Log
		11/23/17 Nickel Liang	First Draft
		12/05/17 Nickel Liang   Minor improvements, Add LED, Add Buzzer
                                Standard Function Naming: RM_{Peripheral}_{Name}
        12/06/17 Nickel Liang   Formatting issue
        01/02/18 Nickel Liang   Minor include change
*******************************************************************************
    NOTE
        Please add log above if you change anything in this file.
        This file is expected to change very very frequently,
        so please keep tracking what you modified so other people can have a
        better idea when they debug their program
*******************************************************************************/

/******************************************************************************
    INCLUDES
*******************************************************************************/
#include "stm32f4xx_hal.h"
#include "cmsis_os.h"
#include "can.h"
#include "dma.h"
#include "fatfs.h"
#include "i2c.h"
#include "sdio.h"
#include "spi.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"
/* USER INCLUDES */
#include "mytype.h"

/******************************************************************************
    VARIABLES
*******************************************************************************/
/* USER VARIABLES */

/******************************************************************************
    DEFINES
*******************************************************************************/
/* USER DEFINITIONS */

/******************************************************************************
    FUNCTIONS
*******************************************************************************/
void SystemClock_Config(void);
void Error_Handler(void);
void MX_FREERTOS_Init(void);

int main(void) {
    /******************************
    USER Configuration
    ******************************/
    RM_LED_RedOn();     //Indicate the board is initializing
    RM_LED_GreenOff();

    /******************************
    MCU Configuration
    ******************************/
    /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
    HAL_Init();

    /* Configure the system clock */
    SystemClock_Config();

    /* Initialize all configured peripherals */
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_CAN1_Init();
    MX_USART1_UART_Init();
    MX_SPI5_Init();
    MX_USART3_UART_Init();
    MX_USART6_UART_Init();
    MX_CAN2_Init();
    MX_TIM5_Init();
    MX_TIM2_Init();
    MX_TIM3_Init();
    MX_TIM4_Init();
    MX_TIM8_Init();
    MX_TIM12_Init();
    MX_USART2_UART_Init();
    //SystemClock_Config(); //This line is generated by CubeMX, but it will crash the program. Ignore it.
    MX_I2C2_Init();
    MX_SPI4_Init();
    MX_SDIO_SD_Init();
    // BSP_SD_Init(); // Initialize SD BSP
    //
    // /******************************
    // PERIPHERALS INITIALIZATION
    // ******************************/
    // RM_SDIO_Mount(); // Mount SD card

    /******************************
    RTOS Configuration
    ******************************/
    /* Call init function for freertos objects (in freertos.c) */
    MX_FREERTOS_Init();

    /* Start scheduler */
    osKernelStart();

    /* We should never get here as control is now taken by the scheduler */
    while (1) {
    }
}

/* System Clock Configuration */
void SystemClock_Config(void) {

    RCC_OscInitTypeDef RCC_OscInitStruct;
    RCC_ClkInitTypeDef RCC_ClkInitStruct;

    __HAL_RCC_PWR_CLK_ENABLE();

    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 12;
    RCC_OscInitStruct.PLL.PLLN = 336;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = 7;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        Error_Handler();
    }

    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK) {
        Error_Handler();
    }

    HAL_SYSTICK_Config(HAL_RCC_GetHCLKFreq()/1000);

    HAL_SYSTICK_CLKSourceConfig(SYSTICK_CLKSOURCE_HCLK);

    /* SysTick_IRQn interrupt configuration */
    HAL_NVIC_SetPriority(SysTick_IRQn, 15, 0);
}

// This is Utility function for printf via USART6
int fputc(int ch, FILE *f) {
    uint8_t temp[1] = {ch};
    HAL_UART_Transmit(&huart6, temp, 1, 2);
    return 1;
}

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM6) {
        HAL_IncTick();
    }
}

void Error_Handler(void) {
    while(1) {
    }
}

#ifdef USE_FULL_ASSERT

void assert_failed(uint8_t* file, uint32_t line) {
}

#endif
